"""Domain entities, value objects, and infrastructure-independent ports."""

from soulmate_core.domain.models import (
    AuditEvent,
    Constraint,
    DerivedModel,
    Evidence,
    EvidenceTargetType,
    Fact,
    Goal,
    Job,
    JobStatus,
    Preference,
    Profile,
    RawEvent,
    Source,
    UserModelSnapshot,
)
from soulmate_core.domain.ports import (
    AuditEventRepository,
    EvidenceRepository,
    JobRepository,
    PersonalModelRepository,
    ProfileRepository,
    RawEventRepository,
    SourceRepository,
    SystemMetadataRepository,
)

__all__ = [
    "AuditEvent",
    "AuditEventRepository",
    "Constraint",
    "DerivedModel",
    "Evidence",
    "EvidenceRepository",
    "EvidenceTargetType",
    "Fact",
    "Goal",
    "Job",
    "JobRepository",
    "JobStatus",
    "PersonalModelRepository",
    "Preference",
    "Profile",
    "ProfileRepository",
    "RawEvent",
    "RawEventRepository",
    "Source",
    "SourceRepository",
    "SystemMetadataRepository",
    "UserModelSnapshot",
]
