"""Infrastructure-independent repository contracts."""

from collections.abc import Collection
from datetime import datetime
from typing import Protocol

from soulmate_core.domain.models import (
    ActiveQuestion,
    ApiCredential,
    AuditEvent,
    Conversation,
    DecisionAdvice,
    DecisionEvent,
    DecisionOption,
    DecisionOutcome,
    DecisionPrediction,
    DecisionResolution,
    DelegationPolicy,
    DelegationRequest,
    DelegationStatus,
    DerivedModel,
    Evidence,
    Job,
    Message,
    PairedDevice,
    PairingToken,
    Preference,
    Profile,
    QuestionAnswer,
    RawEvent,
    ServiceIdentity,
    Source,
    SourceDeletion,
    UserModelSnapshot,
)


class ProfileRepository(Protocol):
    def add(self, profile: Profile) -> None: ...

    def get(self, profile_id: str) -> Profile | None: ...


class SourceRepository(Protocol):
    def add(self, source: Source) -> None: ...

    def get(self, source_id: str) -> Source | None: ...

    def list_for_profile(self, profile_id: str) -> tuple[Source, ...]: ...

    def add_import(
        self,
        source: Source,
        conversations: tuple[Conversation, ...],
        messages: tuple[Message, ...],
        events: tuple[RawEvent, ...],
    ) -> None: ...

    def remove_import(self, profile_id: str, source_id: str) -> SourceDeletion | None: ...


class RawEventRepository(Protocol):
    def add(self, event: RawEvent) -> None: ...

    def get(self, event_id: str) -> RawEvent | None: ...


class ConversationRepository(Protocol):
    def add(self, conversation: Conversation) -> None: ...

    def get(self, conversation_id: str) -> Conversation | None: ...

    def list_for_profile(self, profile_id: str) -> tuple[Conversation, ...]: ...

    def touch(self, conversation_id: str, updated_at: datetime) -> None: ...


class MessageRepository(Protocol):
    def add(self, message: Message) -> None: ...

    def get(self, message_id: str) -> Message | None: ...

    def list_for_conversation(self, conversation_id: str) -> tuple[Message, ...]: ...


class DecisionRepository(Protocol):
    def add(self, decision: DecisionEvent, options: tuple[DecisionOption, ...]) -> None: ...

    def get(self, decision_id: str) -> tuple[DecisionEvent, tuple[DecisionOption, ...]] | None: ...

    def list_for_profile(
        self, profile_id: str
    ) -> tuple[tuple[DecisionEvent, tuple[DecisionOption, ...]], ...]: ...

    def list_resolved(
        self, profile_id: str
    ) -> tuple[tuple[DecisionEvent, tuple[DecisionOption, ...], DecisionResolution], ...]: ...

    def add_prediction(self, prediction: DecisionPrediction) -> None: ...

    def latest_prediction(self, decision_id: str) -> DecisionPrediction | None: ...

    def resolve(self, resolution: DecisionResolution) -> None: ...

    def get_resolution(self, decision_id: str) -> DecisionResolution | None: ...

    def add_advice(self, advice: DecisionAdvice) -> None: ...

    def latest_advice(self, decision_id: str) -> DecisionAdvice | None: ...


class OutcomeRepository(Protocol):
    def add(self, outcome: DecisionOutcome) -> None: ...

    def get_for_decision(self, decision_id: str) -> DecisionOutcome | None: ...

    def list_for_profile(self, profile_id: str) -> tuple[DecisionOutcome, ...]: ...

    def remove_for_decision(self, decision_id: str) -> bool: ...


class ActiveQuestionRepository(Protocol):
    def add(self, question: ActiveQuestion) -> None: ...

    def get(self, question_id: str) -> ActiveQuestion | None: ...

    def list_for_profile(self, profile_id: str) -> tuple[ActiveQuestion, ...]: ...

    def add_answer(self, answer: QuestionAnswer) -> None: ...

    def get_answer(self, question_id: str) -> QuestionAnswer | None: ...


class EvidenceRepository(Protocol):
    def add(self, evidence: Evidence) -> None: ...

    def get(self, evidence_id: str) -> Evidence | None: ...

    def list_for_profile(self, profile_id: str) -> tuple[Evidence, ...]: ...

    def list_for_profile_with_revision(
        self, profile_id: str
    ) -> tuple[tuple[Evidence, ...], int]: ...

    def list_for_target(self, profile_id: str, target_key: str) -> tuple[Evidence, ...]: ...

    def remove(self, evidence_id: str) -> bool: ...

    def current_revision(self, profile_id: str) -> int: ...


class PersonalModelRepository(Protocol):
    def replace(
        self,
        profile_id: str,
        model: DerivedModel,
        evidence_revision: int,
        algorithm_version: str,
        created_at: datetime,
    ) -> UserModelSnapshot: ...

    def latest_snapshot(self, profile_id: str) -> UserModelSnapshot | None: ...

    def list_preferences(self, profile_id: str) -> tuple[Preference, ...]: ...

    def get_preferences(self, profile_id: str, key: str) -> tuple[Preference, ...]: ...


class AuditEventRepository(Protocol):
    def add(self, event: AuditEvent) -> None: ...

    def get(self, event_id: str) -> AuditEvent | None: ...

    def list_for_profile(self, profile_id: str, limit: int = 100) -> tuple[AuditEvent, ...]: ...


class JobRepository(Protocol):
    def enqueue(self, job: Job) -> None: ...

    def get(self, job_id: str) -> Job | None: ...

    def claim_next(
        self, now: datetime, stale_before: datetime, job_types: Collection[str]
    ) -> Job | None: ...

    def mark_succeeded(self, job_id: str, completed_at: datetime) -> None: ...

    def mark_failed(
        self,
        job_id: str,
        error: str,
        failed_at: datetime,
        retry_at: datetime | None = None,
    ) -> None: ...


class PairingTokenRepository(Protocol):
    def add(self, token: PairingToken) -> None: ...

    def get_by_hash(self, token_hash: str) -> PairingToken | None: ...

    def consume(self, token_id: str, device_id: str, consumed_at: datetime) -> bool: ...

    def delete_expired(self, before: datetime) -> int: ...


class PairedDeviceRepository(Protocol):
    def add(self, device: PairedDevice) -> None: ...

    def get(self, device_id: str) -> PairedDevice | None: ...

    def list_for_profile(self, profile_id: str) -> tuple[PairedDevice, ...]: ...

    def touch(self, device_id: str, last_seen_at: datetime) -> None: ...

    def revoke(self, device_id: str, revoked_at: datetime) -> bool: ...


class ServiceIdentityRepository(Protocol):
    def add(self, identity: ServiceIdentity) -> None: ...

    def get(self, identity_id: str) -> ServiceIdentity | None: ...

    def list_for_profile(self, profile_id: str) -> tuple[ServiceIdentity, ...]: ...

    def replace_scopes(self, identity_id: str, scopes: tuple[str, ...]) -> bool: ...

    def revoke(self, identity_id: str, revoked_at: datetime) -> bool: ...


class ApiCredentialRepository(Protocol):
    def add(self, credential: ApiCredential) -> None: ...

    def get(self, credential_id: str) -> ApiCredential | None: ...

    def list_for_identity(self, identity_id: str) -> tuple[ApiCredential, ...]: ...

    def touch(self, credential_id: str, last_used_at: datetime) -> None: ...

    def revoke(self, credential_id: str, revoked_at: datetime) -> bool: ...


class DelegationPolicyRepository(Protocol):
    def upsert(self, policy: DelegationPolicy) -> DelegationPolicy: ...

    def get(self, policy_id: str) -> DelegationPolicy | None: ...

    def get_for_action(
        self, profile_id: str, service_identity_id: str, action_type: str
    ) -> DelegationPolicy | None: ...

    def list_for_profile(self, profile_id: str) -> tuple[DelegationPolicy, ...]: ...

    def remove(self, profile_id: str, policy_id: str) -> bool: ...


class DelegationRequestRepository(Protocol):
    def add(self, request: DelegationRequest) -> None: ...

    def get(self, request_id: str) -> DelegationRequest | None: ...

    def get_by_external_request(
        self, service_identity_id: str, external_request_id: str
    ) -> DelegationRequest | None: ...

    def list_for_profile(self, profile_id: str) -> tuple[DelegationRequest, ...]: ...

    def transition(
        self,
        request_id: str,
        expected_status: DelegationStatus,
        status: DelegationStatus,
        reason_code: str,
        changed_at: datetime,
    ) -> bool: ...


class SystemMetadataRepository(Protocol):
    def get(self, key: str) -> str | None: ...

    def set(self, key: str, value: str, updated_at: datetime) -> None: ...

    def get_or_create(self, key: str, value: str, updated_at: datetime) -> str: ...
